apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whats-on-my-ballot
resources:
  - namespace.yaml
  - config.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
images:
  - name: registry.example.com/whats-on-my-ballot-api
    newName: registry.example.com/whats-on-my-ballot-api
    newTag: replace-before-deploying
  - name: registry.example.com/whats-on-my-ballot-web
    newName: registry.example.com/whats-on-my-ballot-web
    newTag: replace-before-deploying
